// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibzvtssztgzktzpqsiqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlienZ0c3N6dGd6a3R6cHFzaXFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzODQ3MTgsImV4cCI6MjA2NDk2MDcxOH0.iqufgmXBYMuqDSAmUDYGYNHgf_78gfw0qc6fy-GKN7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);